name: CI/CD Pipeline - PixCrypt

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test-push-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 pytest

      # Step 4: Lint & test (optional)
      - name: Run lint and tests
        run: |
          flake8 . || echo "Lint warnings only"
          pytest || echo "No tests yet"

      # Step 5: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      # Step 6: Build & push Docker image
      - name: Build and push Docker image
        run: |
          IMAGE=${{ secrets.DOCKER_HUB_USERNAME }}/pixcrypt:latest
          docker build -t $IMAGE .
          docker push $IMAGE

      # Step 7: SSH into EC2 and trigger deployment script
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.10.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            chmod +x /home/ec2-user/deploy/deploy.sh
            /home/ec2-user/deploy/deploy.sh
