name: CI/CD Pipeline - PixCrypt

# Triggers: push to main, PRs to main, and manual trigger
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build-test-push-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 pytest

      # Step 4: Lint & run tests (optional)
      - name: Lint & Test
        run: |
          flake8 . || echo "Lint warnings only"
          pytest || echo "No tests yet"

      # Step 5: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      # Step 6: Build & push Docker image
      - name: Build & Push Docker Image
        run: |
          IMAGE=${{ secrets.DOCKER_HUB_USERNAME }}/pixcrypt:latest
          docker build -t $IMAGE .
          docker push $IMAGE

      # Step 7: SSH into EC2 and run deploy.sh
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Export Docker username for deploy.sh
            export DOCKER_HUB_USERNAME=${{ secrets.DOCKER_HUB_USERNAME }}

            # Ensure deploy.sh is executable
            chmod +x /home/ubuntu/deploy/deploy.sh

            # Run deploy.sh
            /home/ubuntu/deploy/deploy.sh
